// <auto-generated />
using System;
using Frutos_del_Terraba_Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Frutos_del_Terraba_Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250303215759_DB_Initialization")]
    partial class DB_Initialization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Categoria", b =>
                {
                    b.Property<int>("Id_categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_categoria"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id_categoria");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id_categoria = 1,
                            Descripcion = "Todas las frutas",
                            Nombre = "Frutas"
                        },
                        new
                        {
                            Id_categoria = 2,
                            Descripcion = "Todas las verduras",
                            Nombre = "Verduras"
                        },
                        new
                        {
                            Id_categoria = 3,
                            Descripcion = "Todas las verduras",
                            Nombre = "Legumbres"
                        });
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.DetallesPedido", b =>
                {
                    b.Property<int>("Id_detalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_detalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Id_pedido")
                        .HasColumnType("int");

                    b.Property<int>("Id_producto")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id_detalle");

                    b.HasIndex("Id_pedido");

                    b.HasIndex("Id_producto");

                    b.ToTable("DetallesPedidos");

                    b.HasData(
                        new
                        {
                            Id_detalle = 1,
                            Cantidad = 40,
                            Id_pedido = 1,
                            Id_producto = 1,
                            Observaciones = ""
                        },
                        new
                        {
                            Id_detalle = 2,
                            Cantidad = 46,
                            Id_pedido = 1,
                            Id_producto = 2,
                            Observaciones = ""
                        },
                        new
                        {
                            Id_detalle = 3,
                            Cantidad = 50,
                            Id_pedido = 1,
                            Id_producto = 3,
                            Observaciones = ""
                        },
                        new
                        {
                            Id_detalle = 4,
                            Cantidad = 50,
                            Id_pedido = 2,
                            Id_producto = 4,
                            Observaciones = ""
                        },
                        new
                        {
                            Id_detalle = 5,
                            Cantidad = 50,
                            Id_pedido = 3,
                            Id_producto = 5,
                            Observaciones = ""
                        },
                        new
                        {
                            Id_detalle = 6,
                            Cantidad = 100,
                            Id_pedido = 3,
                            Id_producto = 6,
                            Observaciones = ""
                        },
                        new
                        {
                            Id_detalle = 7,
                            Cantidad = 100,
                            Id_pedido = 4,
                            Id_producto = 7,
                            Observaciones = ""
                        });
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Distribucion", b =>
                {
                    b.Property<int>("Id_distribucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_distribucion"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Id_inventario")
                        .HasColumnType("int");

                    b.HasKey("Id_distribucion");

                    b.HasIndex("Id_inventario");

                    b.ToTable("Distribuciones");

                    b.HasData(
                        new
                        {
                            Id_distribucion = 1,
                            Cantidad = 10,
                            Destino = "Supermercado A",
                            Id_inventario = 1
                        },
                        new
                        {
                            Id_distribucion = 2,
                            Cantidad = 15,
                            Destino = "Supermercado B",
                            Id_inventario = 2
                        },
                        new
                        {
                            Id_distribucion = 3,
                            Cantidad = 5,
                            Destino = "Frutería C",
                            Id_inventario = 3
                        },
                        new
                        {
                            Id_distribucion = 4,
                            Cantidad = 25,
                            Destino = "Verdulería D",
                            Id_inventario = 4
                        },
                        new
                        {
                            Id_distribucion = 5,
                            Cantidad = 30,
                            Destino = "Tienda E",
                            Id_inventario = 5
                        },
                        new
                        {
                            Id_distribucion = 6,
                            Cantidad = 40,
                            Destino = "Mercado F",
                            Id_inventario = 6
                        },
                        new
                        {
                            Id_distribucion = 7,
                            Cantidad = 50,
                            Destino = "Comedor G",
                            Id_inventario = 7
                        });
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Inventario", b =>
                {
                    b.Property<int>("Id_inventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_inventario"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Id_producto")
                        .HasColumnType("int");

                    b.HasKey("Id_inventario");

                    b.HasIndex("Id_producto");

                    b.ToTable("Inventarios");

                    b.HasData(
                        new
                        {
                            Id_inventario = 1,
                            Cantidad = 30,
                            Id_producto = 1
                        },
                        new
                        {
                            Id_inventario = 2,
                            Cantidad = 25,
                            Id_producto = 2
                        },
                        new
                        {
                            Id_inventario = 3,
                            Cantidad = 20,
                            Id_producto = 3
                        },
                        new
                        {
                            Id_inventario = 4,
                            Cantidad = 50,
                            Id_producto = 4
                        },
                        new
                        {
                            Id_inventario = 5,
                            Cantidad = 60,
                            Id_producto = 5
                        },
                        new
                        {
                            Id_inventario = 6,
                            Cantidad = 80,
                            Id_producto = 6
                        },
                        new
                        {
                            Id_inventario = 7,
                            Cantidad = 90,
                            Id_producto = 7
                        });
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Pedido", b =>
                {
                    b.Property<int>("Id_pedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_pedido"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_proveedor")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id_pedido");

                    b.HasIndex("Id_proveedor");

                    b.HasIndex("UserId");

                    b.ToTable("Pedidos");

                    b.HasData(
                        new
                        {
                            Id_pedido = 1,
                            Fecha = new DateTime(2025, 3, 3, 15, 57, 58, 659, DateTimeKind.Local).AddTicks(6742),
                            Id_proveedor = 1,
                            UserId = "7cba396e-ef44-45d4-8ca8-cbe90733d21e"
                        },
                        new
                        {
                            Id_pedido = 2,
                            Fecha = new DateTime(2025, 3, 3, 15, 57, 58, 659, DateTimeKind.Local).AddTicks(6767),
                            Id_proveedor = 1,
                            UserId = "7cba396e-ef44-45d4-8ca8-cbe90733d21e"
                        },
                        new
                        {
                            Id_pedido = 3,
                            Fecha = new DateTime(2025, 3, 3, 15, 57, 58, 659, DateTimeKind.Local).AddTicks(6769),
                            Id_proveedor = 2,
                            UserId = "7cba396e-ef44-45d4-8ca8-cbe90733d21e"
                        },
                        new
                        {
                            Id_pedido = 4,
                            Fecha = new DateTime(2025, 3, 3, 15, 57, 58, 659, DateTimeKind.Local).AddTicks(6771),
                            Id_proveedor = 2,
                            UserId = "7cba396e-ef44-45d4-8ca8-cbe90733d21e"
                        });
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Producto", b =>
                {
                    b.Property<int>("Id_producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_producto"));

                    b.Property<int>("Id_categoria")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id_producto");

                    b.HasIndex("Id_categoria");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id_producto = 1,
                            Id_categoria = 3,
                            Nombre = "Culantro Coyote",
                            Stock = 40
                        },
                        new
                        {
                            Id_producto = 2,
                            Id_categoria = 3,
                            Nombre = "Tonillo",
                            Stock = 46
                        },
                        new
                        {
                            Id_producto = 3,
                            Id_categoria = 3,
                            Nombre = "Apio",
                            Stock = 50
                        },
                        new
                        {
                            Id_producto = 4,
                            Id_categoria = 1,
                            Nombre = "Papaya",
                            Stock = 50
                        },
                        new
                        {
                            Id_producto = 5,
                            Id_categoria = 1,
                            Nombre = "Manzana Verde",
                            Stock = 50
                        },
                        new
                        {
                            Id_producto = 6,
                            Id_categoria = 1,
                            Nombre = "Manzana Roja",
                            Stock = 100
                        },
                        new
                        {
                            Id_producto = 7,
                            Id_categoria = 2,
                            Nombre = "Brocoli",
                            Stock = 100
                        });
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Proveedor", b =>
                {
                    b.Property<int>("Id_proveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_proveedor"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_proveedor");

                    b.ToTable("Proveedores");

                    b.HasData(
                        new
                        {
                            Id_proveedor = 1,
                            Apellidos = "Mata Rabbe",
                            Email = "gustabo@gmial.com",
                            Nombre = "Gustavo",
                            Telefono = "85637049"
                        },
                        new
                        {
                            Id_proveedor = 2,
                            Apellidos = "Tencio Solano",
                            Email = "elena@gmial.com",
                            Nombre = "Elena",
                            Telefono = "98540244"
                        });
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Reporte", b =>
                {
                    b.Property<int>("Id_reporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_reporte"));

                    b.Property<int>("Cantidad_reportada")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_producto")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id_reporte");

                    b.HasIndex("Id_producto");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d86e1426-a604-499c-b4d2-ad5023a6b42d",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "ca645775-80c6-44a5-b5ab-079a07cd521e",
                            Name = "Empleado",
                            NormalizedName = "EMPLEADO"
                        },
                        new
                        {
                            Id = "aecad1ec-a292-47f0-b58c-7b3b7fcce86a",
                            Name = "Distribuidor",
                            NormalizedName = "DISTRIBUIDOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7cba396e-ef44-45d4-8ca8-cbe90733d21e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "35eb9634-0265-49df-9db7-f19472c45751",
                            Email = "fabian@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "FABIAN@GMAIL.COM",
                            NormalizedUserName = "FABIAN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDrXJ5R8HyW5N3PNAf74XmO+pO0rpXGxiVkNRcVw0AOzM03KEo9fPcnE6sXfx4Cn8Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "160f00ea-0d4a-4f55-98e3-435627c81f46",
                            TwoFactorEnabled = false,
                            UserName = "fabian@gmail.com"
                        },
                        new
                        {
                            Id = "8ea58a73-f3c8-4b9a-bb9f-980f00e9bb43",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "be4323f7-2220-43ce-8104-e01fd3c1986e",
                            Email = "cristopher@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CRISTOPHER@GMAIL.COM",
                            NormalizedUserName = "CRISTOPHER@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOavrtmtV+QrmYgc0nMnUzGIyxNMVFf11rrRRGPv4hV6hxskWDqaeXfHrHaRfHTaEA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "70129b1e-5385-4bef-a31c-fe1492b99563",
                            TwoFactorEnabled = false,
                            UserName = "cristopher@gmail.com"
                        },
                        new
                        {
                            Id = "5900c253-7075-4165-95de-79bc9952f055",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "04f67baa-8098-437f-a53f-81cce1bbd059",
                            Email = "rodolfo@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "RODOLFO@GMAIL.COM",
                            NormalizedUserName = "RODOLFO@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELaKytraFxqY/yHjLMX3WVsHZCoThOMpTQIabFaEtfU8rZHjypif52LF6DU6MmX4ww==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a39be971-03ad-4830-afdd-76c90d112fc7",
                            TwoFactorEnabled = false,
                            UserName = "rodolfo@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "7cba396e-ef44-45d4-8ca8-cbe90733d21e",
                            RoleId = "d86e1426-a604-499c-b4d2-ad5023a6b42d"
                        },
                        new
                        {
                            UserId = "8ea58a73-f3c8-4b9a-bb9f-980f00e9bb43",
                            RoleId = "ca645775-80c6-44a5-b5ab-079a07cd521e"
                        },
                        new
                        {
                            UserId = "5900c253-7075-4165-95de-79bc9952f055",
                            RoleId = "aecad1ec-a292-47f0-b58c-7b3b7fcce86a"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.DetallesPedido", b =>
                {
                    b.HasOne("Frutos_del_Terraba_Api.Models.Pedido", "Pedido")
                        .WithMany("DetallesPedidos")
                        .HasForeignKey("Id_pedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Frutos_del_Terraba_Api.Models.Producto", "Producto")
                        .WithMany("DetallesPedidos")
                        .HasForeignKey("Id_producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Distribucion", b =>
                {
                    b.HasOne("Frutos_del_Terraba_Api.Models.Inventario", "Inventario")
                        .WithMany("Distribuciones")
                        .HasForeignKey("Id_inventario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventario");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Inventario", b =>
                {
                    b.HasOne("Frutos_del_Terraba_Api.Models.Producto", "Producto")
                        .WithMany("Inventarios")
                        .HasForeignKey("Id_producto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Pedido", b =>
                {
                    b.HasOne("Frutos_del_Terraba_Api.Models.Proveedor", "Proveedor")
                        .WithMany("Pedidos")
                        .HasForeignKey("Id_proveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Producto", b =>
                {
                    b.HasOne("Frutos_del_Terraba_Api.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("Id_categoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Reporte", b =>
                {
                    b.HasOne("Frutos_del_Terraba_Api.Models.Producto", "Producto")
                        .WithMany("Reportes")
                        .HasForeignKey("Id_producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Inventario", b =>
                {
                    b.Navigation("Distribuciones");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Pedido", b =>
                {
                    b.Navigation("DetallesPedidos");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Producto", b =>
                {
                    b.Navigation("DetallesPedidos");

                    b.Navigation("Inventarios");

                    b.Navigation("Reportes");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Proveedor", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
