// <auto-generated />
using System;
using Frutos_del_Terraba_Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Frutos_del_Terraba_Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250326032236_add_column_state_to_pedido")]
    partial class add_column_state_to_pedido
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Categoria", b =>
                {
                    b.Property<int>("Id_categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_categoria"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id_categoria");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id_categoria = 1,
                            Descripcion = "Todas las frutas",
                            Nombre = "Frutas"
                        },
                        new
                        {
                            Id_categoria = 2,
                            Descripcion = "Todas las verduras",
                            Nombre = "Verduras"
                        },
                        new
                        {
                            Id_categoria = 3,
                            Descripcion = "Todas las verduras",
                            Nombre = "Legumbres"
                        });
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.DetallesDistribucion", b =>
                {
                    b.Property<int>("Id_detalle_distribucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_detalle_distribucion"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Id_distribucion")
                        .HasColumnType("int");

                    b.Property<int>("Id_inventario")
                        .HasColumnType("int");

                    b.HasKey("Id_detalle_distribucion");

                    b.HasIndex("Id_distribucion");

                    b.HasIndex("Id_inventario");

                    b.ToTable("DetallesDistribuciones");

                    b.HasData(
                        new
                        {
                            Id_detalle_distribucion = 1,
                            Cantidad = 10,
                            Id_distribucion = 1,
                            Id_inventario = 1
                        },
                        new
                        {
                            Id_detalle_distribucion = 2,
                            Cantidad = 15,
                            Id_distribucion = 1,
                            Id_inventario = 2
                        },
                        new
                        {
                            Id_detalle_distribucion = 3,
                            Cantidad = 5,
                            Id_distribucion = 2,
                            Id_inventario = 3
                        },
                        new
                        {
                            Id_detalle_distribucion = 4,
                            Cantidad = 25,
                            Id_distribucion = 2,
                            Id_inventario = 1
                        },
                        new
                        {
                            Id_detalle_distribucion = 5,
                            Cantidad = 30,
                            Id_distribucion = 2,
                            Id_inventario = 5
                        },
                        new
                        {
                            Id_detalle_distribucion = 6,
                            Cantidad = 40,
                            Id_distribucion = 3,
                            Id_inventario = 6
                        },
                        new
                        {
                            Id_detalle_distribucion = 7,
                            Cantidad = 50,
                            Id_distribucion = 3,
                            Id_inventario = 7
                        });
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.DetallesPedido", b =>
                {
                    b.Property<int>("Id_detalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_detalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Id_pedido")
                        .HasColumnType("int");

                    b.Property<int>("Id_producto")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id_detalle");

                    b.HasIndex("Id_pedido");

                    b.HasIndex("Id_producto");

                    b.ToTable("DetallesPedidos");

                    b.HasData(
                        new
                        {
                            Id_detalle = 1,
                            Cantidad = 40,
                            Id_pedido = 1,
                            Id_producto = 1,
                            Observaciones = ""
                        },
                        new
                        {
                            Id_detalle = 2,
                            Cantidad = 46,
                            Id_pedido = 1,
                            Id_producto = 2,
                            Observaciones = ""
                        },
                        new
                        {
                            Id_detalle = 3,
                            Cantidad = 50,
                            Id_pedido = 1,
                            Id_producto = 3,
                            Observaciones = ""
                        },
                        new
                        {
                            Id_detalle = 4,
                            Cantidad = 50,
                            Id_pedido = 2,
                            Id_producto = 4,
                            Observaciones = ""
                        },
                        new
                        {
                            Id_detalle = 5,
                            Cantidad = 50,
                            Id_pedido = 3,
                            Id_producto = 5,
                            Observaciones = ""
                        },
                        new
                        {
                            Id_detalle = 6,
                            Cantidad = 100,
                            Id_pedido = 3,
                            Id_producto = 6,
                            Observaciones = ""
                        },
                        new
                        {
                            Id_detalle = 7,
                            Cantidad = 100,
                            Id_pedido = 4,
                            Id_producto = 7,
                            Observaciones = ""
                        });
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Distribucion", b =>
                {
                    b.Property<int>("Id_distribucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_distribucion"));

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id_distribucion");

                    b.HasIndex("UserId");

                    b.ToTable("Distribuciones");

                    b.HasData(
                        new
                        {
                            Id_distribucion = 1,
                            Destino = "Supermercado A",
                            Observaciones = "Es una cargamento que hay que transportar con cuidado",
                            Ubicacion = "Rúa 21",
                            UserId = "89f1dd0a-89b9-43eb-9942-0eb1ad9aa080"
                        },
                        new
                        {
                            Id_distribucion = 2,
                            Destino = "Supermercado ",
                            Observaciones = "",
                            Ubicacion = "El Boule Garage",
                            UserId = "b944e074-7724-4999-9e2d-11835200c4ef"
                        },
                        new
                        {
                            Id_distribucion = 3,
                            Destino = "Frutería C",
                            Observaciones = "Un buen pedido",
                            Ubicacion = "Lomito's Grill - Steak House",
                            UserId = "89f1dd0a-89b9-43eb-9942-0eb1ad9aa080"
                        });
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Inventario", b =>
                {
                    b.Property<int>("Id_inventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_inventario"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Id_producto")
                        .HasColumnType("int");

                    b.HasKey("Id_inventario");

                    b.HasIndex("Id_producto");

                    b.ToTable("Inventarios");

                    b.HasData(
                        new
                        {
                            Id_inventario = 1,
                            Cantidad = 330,
                            Id_producto = 1
                        },
                        new
                        {
                            Id_inventario = 2,
                            Cantidad = 325,
                            Id_producto = 2
                        },
                        new
                        {
                            Id_inventario = 3,
                            Cantidad = 320,
                            Id_producto = 3
                        },
                        new
                        {
                            Id_inventario = 4,
                            Cantidad = 350,
                            Id_producto = 4
                        },
                        new
                        {
                            Id_inventario = 5,
                            Cantidad = 360,
                            Id_producto = 5
                        },
                        new
                        {
                            Id_inventario = 6,
                            Cantidad = 380,
                            Id_producto = 6
                        },
                        new
                        {
                            Id_inventario = 7,
                            Cantidad = 390,
                            Id_producto = 7
                        });
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Pedido", b =>
                {
                    b.Property<int>("Id_pedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_pedido"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_proveedor")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id_pedido");

                    b.HasIndex("Id_proveedor");

                    b.HasIndex("UserId");

                    b.ToTable("Pedidos");

                    b.HasData(
                        new
                        {
                            Id_pedido = 1,
                            Estado = false,
                            Fecha = new DateTime(2025, 3, 25, 21, 22, 35, 895, DateTimeKind.Local).AddTicks(8965),
                            Id_proveedor = 1,
                            UserId = "89f1dd0a-89b9-43eb-9942-0eb1ad9aa080"
                        },
                        new
                        {
                            Id_pedido = 2,
                            Estado = false,
                            Fecha = new DateTime(2025, 3, 25, 21, 22, 35, 895, DateTimeKind.Local).AddTicks(8987),
                            Id_proveedor = 1,
                            UserId = "89f1dd0a-89b9-43eb-9942-0eb1ad9aa080"
                        },
                        new
                        {
                            Id_pedido = 3,
                            Estado = false,
                            Fecha = new DateTime(2025, 3, 25, 21, 22, 35, 895, DateTimeKind.Local).AddTicks(8988),
                            Id_proveedor = 2,
                            UserId = "89f1dd0a-89b9-43eb-9942-0eb1ad9aa080"
                        },
                        new
                        {
                            Id_pedido = 4,
                            Estado = false,
                            Fecha = new DateTime(2025, 3, 25, 21, 22, 35, 895, DateTimeKind.Local).AddTicks(8989),
                            Id_proveedor = 2,
                            UserId = "89f1dd0a-89b9-43eb-9942-0eb1ad9aa080"
                        });
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Producto", b =>
                {
                    b.Property<int>("Id_producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_producto"));

                    b.Property<int>("Id_categoria")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id_producto");

                    b.HasIndex("Id_categoria");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id_producto = 1,
                            Id_categoria = 3,
                            Nombre = "Culantro Coyote"
                        },
                        new
                        {
                            Id_producto = 2,
                            Id_categoria = 3,
                            Nombre = "Tonillo"
                        },
                        new
                        {
                            Id_producto = 3,
                            Id_categoria = 3,
                            Nombre = "Apio"
                        },
                        new
                        {
                            Id_producto = 4,
                            Id_categoria = 1,
                            Nombre = "Papaya"
                        },
                        new
                        {
                            Id_producto = 5,
                            Id_categoria = 1,
                            Nombre = "Manzana Verde"
                        },
                        new
                        {
                            Id_producto = 6,
                            Id_categoria = 1,
                            Nombre = "Manzana Roja"
                        },
                        new
                        {
                            Id_producto = 7,
                            Id_categoria = 2,
                            Nombre = "Brocoli"
                        });
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Proveedor", b =>
                {
                    b.Property<int>("Id_proveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_proveedor"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_proveedor");

                    b.ToTable("Proveedores");

                    b.HasData(
                        new
                        {
                            Id_proveedor = 1,
                            Apellidos = "Mata Rabbe",
                            Email = "gustabo@gmial.com",
                            Nombre = "Gustavo",
                            Telefono = "85637049"
                        },
                        new
                        {
                            Id_proveedor = 2,
                            Apellidos = "Tencio Solano",
                            Email = "elena@gmial.com",
                            Nombre = "Elena",
                            Telefono = "98540244"
                        });
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Reporte", b =>
                {
                    b.Property<int>("Id_reporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_reporte"));

                    b.Property<int>("Cantidad_reportada")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_producto")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id_reporte");

                    b.HasIndex("Id_producto");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d9ef6f11-555d-4e1d-a904-cc79bfc6af70",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "5da2f21c-ddd4-4ef5-8522-87c89ab24a5b",
                            Name = "Empleado",
                            NormalizedName = "EMPLEADO"
                        },
                        new
                        {
                            Id = "3f3c70b6-d761-448a-8f97-e9a5656c4cfb",
                            Name = "Distribuidor",
                            NormalizedName = "DISTRIBUIDOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "89f1dd0a-89b9-43eb-9942-0eb1ad9aa080",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bfd180d9-2398-452e-bf5d-8451bd64fcc7",
                            Email = "fabian@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "FABIAN@GMAIL.COM",
                            NormalizedUserName = "FABIAN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJXxWtz2lHWt0uEiOWqIFzEwFqbVMCk2Yu9A06gt3nXJazWA1Ys7iiU3PbcmhRIdAg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "411d6224-9bbb-4bc6-984e-997622acca07",
                            TwoFactorEnabled = false,
                            UserName = "fabian@gmail.com"
                        },
                        new
                        {
                            Id = "b944e074-7724-4999-9e2d-11835200c4ef",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9de8deee-8941-49b7-aa4c-a0eea6455c58",
                            Email = "cristopher@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CRISTOPHER@GMAIL.COM",
                            NormalizedUserName = "CRISTOPHER@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPhFqlUEKHW8oEz+VGLRdRVKGQo9UBjAK4ZEKUK4BB+kQw8GfWHtBXWC0mmAqIVOrw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a7b6c4e3-57ce-4128-9166-d69d99dffae0",
                            TwoFactorEnabled = false,
                            UserName = "cristopher@gmail.com"
                        },
                        new
                        {
                            Id = "c6bd8445-378e-4eb6-a62d-1740c14957cc",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1e8a3148-de68-41d1-8323-6a7632ba777f",
                            Email = "rodolfo@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "RODOLFO@GMAIL.COM",
                            NormalizedUserName = "RODOLFO@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENSBZnl6drrA/ifPGAhj4KuiWGzRyTTFmS+/h7r0jFXozjz7JG365+zqLjC+Wc+OFw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ef68e0ba-0d27-4500-8249-6655b95fe43c",
                            TwoFactorEnabled = false,
                            UserName = "rodolfo@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "89f1dd0a-89b9-43eb-9942-0eb1ad9aa080",
                            RoleId = "d9ef6f11-555d-4e1d-a904-cc79bfc6af70"
                        },
                        new
                        {
                            UserId = "b944e074-7724-4999-9e2d-11835200c4ef",
                            RoleId = "5da2f21c-ddd4-4ef5-8522-87c89ab24a5b"
                        },
                        new
                        {
                            UserId = "c6bd8445-378e-4eb6-a62d-1740c14957cc",
                            RoleId = "3f3c70b6-d761-448a-8f97-e9a5656c4cfb"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.DetallesDistribucion", b =>
                {
                    b.HasOne("Frutos_del_Terraba_Api.Models.Distribucion", "Distribucion")
                        .WithMany("DetallesDistribuciones")
                        .HasForeignKey("Id_distribucion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Frutos_del_Terraba_Api.Models.Inventario", "Inventario")
                        .WithMany("DetallesDistribuciones")
                        .HasForeignKey("Id_inventario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Distribucion");

                    b.Navigation("Inventario");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.DetallesPedido", b =>
                {
                    b.HasOne("Frutos_del_Terraba_Api.Models.Pedido", "Pedido")
                        .WithMany("DetallesPedidos")
                        .HasForeignKey("Id_pedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Frutos_del_Terraba_Api.Models.Producto", "Producto")
                        .WithMany("DetallesPedidos")
                        .HasForeignKey("Id_producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Distribucion", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Inventario", b =>
                {
                    b.HasOne("Frutos_del_Terraba_Api.Models.Producto", "Producto")
                        .WithMany("Inventarios")
                        .HasForeignKey("Id_producto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Pedido", b =>
                {
                    b.HasOne("Frutos_del_Terraba_Api.Models.Proveedor", "Proveedor")
                        .WithMany("Pedidos")
                        .HasForeignKey("Id_proveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Producto", b =>
                {
                    b.HasOne("Frutos_del_Terraba_Api.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("Id_categoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Reporte", b =>
                {
                    b.HasOne("Frutos_del_Terraba_Api.Models.Producto", "Producto")
                        .WithMany("Reportes")
                        .HasForeignKey("Id_producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Distribucion", b =>
                {
                    b.Navigation("DetallesDistribuciones");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Inventario", b =>
                {
                    b.Navigation("DetallesDistribuciones");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Pedido", b =>
                {
                    b.Navigation("DetallesPedidos");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Producto", b =>
                {
                    b.Navigation("DetallesPedidos");

                    b.Navigation("Inventarios");

                    b.Navigation("Reportes");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Proveedor", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
