// <auto-generated />
using System;
using Frutos_del_Terraba_Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Frutos_del_Terraba_Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Categoria", b =>
                {
                    b.Property<int>("Id_categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_categoria"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id_categoria");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id_categoria = 1,
                            Descripcion = "Todas las frutas",
                            Nombre = "Frutas"
                        },
                        new
                        {
                            Id_categoria = 2,
                            Descripcion = "Todas las verduras",
                            Nombre = "Verduras"
                        },
                        new
                        {
                            Id_categoria = 3,
                            Descripcion = "Todas las verduras",
                            Nombre = "Legumbres"
                        });
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.DetallesDistribucion", b =>
                {
                    b.Property<int>("Id_detalle_distribucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_detalle_distribucion"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Id_distribucion")
                        .HasColumnType("int");

                    b.Property<int>("Id_inventario")
                        .HasColumnType("int");

                    b.HasKey("Id_detalle_distribucion");

                    b.HasIndex("Id_distribucion");

                    b.HasIndex("Id_inventario");

                    b.ToTable("DetallesDistribuciones");

                    b.HasData(
                        new
                        {
                            Id_detalle_distribucion = 1,
                            Cantidad = 10,
                            Id_distribucion = 1,
                            Id_inventario = 1
                        },
                        new
                        {
                            Id_detalle_distribucion = 2,
                            Cantidad = 15,
                            Id_distribucion = 1,
                            Id_inventario = 2
                        },
                        new
                        {
                            Id_detalle_distribucion = 3,
                            Cantidad = 5,
                            Id_distribucion = 2,
                            Id_inventario = 3
                        },
                        new
                        {
                            Id_detalle_distribucion = 4,
                            Cantidad = 25,
                            Id_distribucion = 2,
                            Id_inventario = 1
                        },
                        new
                        {
                            Id_detalle_distribucion = 5,
                            Cantidad = 30,
                            Id_distribucion = 2,
                            Id_inventario = 5
                        },
                        new
                        {
                            Id_detalle_distribucion = 6,
                            Cantidad = 40,
                            Id_distribucion = 3,
                            Id_inventario = 6
                        },
                        new
                        {
                            Id_detalle_distribucion = 7,
                            Cantidad = 50,
                            Id_distribucion = 3,
                            Id_inventario = 7
                        });
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.DetallesPedido", b =>
                {
                    b.Property<int>("Id_detalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_detalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Id_pedido")
                        .HasColumnType("int");

                    b.Property<int>("Id_producto")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id_detalle");

                    b.HasIndex("Id_pedido");

                    b.HasIndex("Id_producto");

                    b.ToTable("DetallesPedidos");

                    b.HasData(
                        new
                        {
                            Id_detalle = 1,
                            Cantidad = 40,
                            Id_pedido = 1,
                            Id_producto = 1,
                            Observaciones = ""
                        },
                        new
                        {
                            Id_detalle = 2,
                            Cantidad = 46,
                            Id_pedido = 1,
                            Id_producto = 2,
                            Observaciones = ""
                        },
                        new
                        {
                            Id_detalle = 3,
                            Cantidad = 50,
                            Id_pedido = 1,
                            Id_producto = 3,
                            Observaciones = ""
                        },
                        new
                        {
                            Id_detalle = 4,
                            Cantidad = 50,
                            Id_pedido = 2,
                            Id_producto = 4,
                            Observaciones = ""
                        },
                        new
                        {
                            Id_detalle = 5,
                            Cantidad = 50,
                            Id_pedido = 3,
                            Id_producto = 5,
                            Observaciones = ""
                        },
                        new
                        {
                            Id_detalle = 6,
                            Cantidad = 100,
                            Id_pedido = 3,
                            Id_producto = 6,
                            Observaciones = ""
                        },
                        new
                        {
                            Id_detalle = 7,
                            Cantidad = 100,
                            Id_pedido = 4,
                            Id_producto = 7,
                            Observaciones = ""
                        });
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Distribucion", b =>
                {
                    b.Property<int>("Id_distribucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_distribucion"));

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id_distribucion");

                    b.HasIndex("UserId");

                    b.ToTable("Distribuciones");

                    b.HasData(
                        new
                        {
                            Id_distribucion = 1,
                            Destino = "Supermercado A",
                            Observaciones = "Es una cargamento que hay que transportar con cuidado",
                            Ubicacion = "Rúa 21",
                            UserId = "97b3151c-f939-4f89-9679-1f37116740d1"
                        },
                        new
                        {
                            Id_distribucion = 2,
                            Destino = "Supermercado ",
                            Observaciones = "",
                            Ubicacion = "El Boule Garage",
                            UserId = "f1e29e01-a4f9-4be5-8c57-9b248d16570c"
                        },
                        new
                        {
                            Id_distribucion = 3,
                            Destino = "Frutería C",
                            Observaciones = "Un buen pedido",
                            Ubicacion = "Lomito's Grill - Steak House",
                            UserId = "97b3151c-f939-4f89-9679-1f37116740d1"
                        });
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Inventario", b =>
                {
                    b.Property<int>("Id_inventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_inventario"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Id_producto")
                        .HasColumnType("int");

                    b.HasKey("Id_inventario");

                    b.HasIndex("Id_producto");

                    b.ToTable("Inventarios");

                    b.HasData(
                        new
                        {
                            Id_inventario = 1,
                            Cantidad = 330,
                            Id_producto = 1
                        },
                        new
                        {
                            Id_inventario = 2,
                            Cantidad = 325,
                            Id_producto = 2
                        },
                        new
                        {
                            Id_inventario = 3,
                            Cantidad = 320,
                            Id_producto = 3
                        },
                        new
                        {
                            Id_inventario = 4,
                            Cantidad = 350,
                            Id_producto = 4
                        },
                        new
                        {
                            Id_inventario = 5,
                            Cantidad = 360,
                            Id_producto = 5
                        },
                        new
                        {
                            Id_inventario = 6,
                            Cantidad = 380,
                            Id_producto = 6
                        },
                        new
                        {
                            Id_inventario = 7,
                            Cantidad = 390,
                            Id_producto = 7
                        });
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Pedido", b =>
                {
                    b.Property<int>("Id_pedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_pedido"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_proveedor")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id_pedido");

                    b.HasIndex("Id_proveedor");

                    b.HasIndex("UserId");

                    b.ToTable("Pedidos");

                    b.HasData(
                        new
                        {
                            Id_pedido = 1,
                            Estado = false,
                            Fecha = new DateTime(2025, 3, 26, 21, 10, 35, 445, DateTimeKind.Local).AddTicks(9397),
                            Id_proveedor = 1,
                            UserId = "97b3151c-f939-4f89-9679-1f37116740d1"
                        },
                        new
                        {
                            Id_pedido = 2,
                            Estado = false,
                            Fecha = new DateTime(2025, 3, 26, 21, 10, 35, 445, DateTimeKind.Local).AddTicks(9414),
                            Id_proveedor = 1,
                            UserId = "97b3151c-f939-4f89-9679-1f37116740d1"
                        },
                        new
                        {
                            Id_pedido = 3,
                            Estado = false,
                            Fecha = new DateTime(2025, 3, 26, 21, 10, 35, 445, DateTimeKind.Local).AddTicks(9416),
                            Id_proveedor = 2,
                            UserId = "97b3151c-f939-4f89-9679-1f37116740d1"
                        },
                        new
                        {
                            Id_pedido = 4,
                            Estado = false,
                            Fecha = new DateTime(2025, 3, 26, 21, 10, 35, 445, DateTimeKind.Local).AddTicks(9418),
                            Id_proveedor = 2,
                            UserId = "97b3151c-f939-4f89-9679-1f37116740d1"
                        });
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Producto", b =>
                {
                    b.Property<int>("Id_producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_producto"));

                    b.Property<int>("Id_categoria")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id_producto");

                    b.HasIndex("Id_categoria");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id_producto = 1,
                            Id_categoria = 3,
                            Nombre = "Culantro Coyote"
                        },
                        new
                        {
                            Id_producto = 2,
                            Id_categoria = 3,
                            Nombre = "Tonillo"
                        },
                        new
                        {
                            Id_producto = 3,
                            Id_categoria = 3,
                            Nombre = "Apio"
                        },
                        new
                        {
                            Id_producto = 4,
                            Id_categoria = 1,
                            Nombre = "Papaya"
                        },
                        new
                        {
                            Id_producto = 5,
                            Id_categoria = 1,
                            Nombre = "Manzana Verde"
                        },
                        new
                        {
                            Id_producto = 6,
                            Id_categoria = 1,
                            Nombre = "Manzana Roja"
                        },
                        new
                        {
                            Id_producto = 7,
                            Id_categoria = 2,
                            Nombre = "Brocoli"
                        });
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Proveedor", b =>
                {
                    b.Property<int>("Id_proveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_proveedor"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_proveedor");

                    b.ToTable("Proveedores");

                    b.HasData(
                        new
                        {
                            Id_proveedor = 1,
                            Apellidos = "Mata Rabbe",
                            Email = "gustabo@gmial.com",
                            Nombre = "Gustavo",
                            Telefono = "85637049"
                        },
                        new
                        {
                            Id_proveedor = 2,
                            Apellidos = "Tencio Solano",
                            Email = "elena@gmial.com",
                            Nombre = "Elena",
                            Telefono = "98540244"
                        });
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Reporte", b =>
                {
                    b.Property<int>("Id_reporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_reporte"));

                    b.Property<int>("Cantidad_reportada")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_producto")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id_reporte");

                    b.HasIndex("Id_producto");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "32f5c337-16be-44ad-8c87-d13d7ddeac28",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "aa61e93c-ab9d-46f4-b3a7-ef5463a9237b",
                            Name = "Empleado",
                            NormalizedName = "EMPLEADO"
                        },
                        new
                        {
                            Id = "aa786d24-1a3f-4f57-b7f9-2a19a99d4823",
                            Name = "Distribuidor",
                            NormalizedName = "DISTRIBUIDOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "97b3151c-f939-4f89-9679-1f37116740d1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "16700886-8f24-4e8f-8dc7-0b99b0e9dbea",
                            Email = "fabian@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "FABIAN@GMAIL.COM",
                            NormalizedUserName = "FABIAN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOvSQCwPOVrlv4h7tgyfQykjWZ2LKYISK+cfRwqyVNEV/xdfei40oyZn/VJ3aR+jYg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "30832c51-f601-49b9-a008-416059ac6b44",
                            TwoFactorEnabled = false,
                            UserName = "fabian@gmail.com"
                        },
                        new
                        {
                            Id = "f1e29e01-a4f9-4be5-8c57-9b248d16570c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6bc0da31-16fe-4688-86af-66eae89a0dde",
                            Email = "cristopher@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CRISTOPHER@GMAIL.COM",
                            NormalizedUserName = "CRISTOPHER@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECHmFGKBdwjui2ST5nPPXYEOLuNI3icv4zsp4/S5AVDq/koG1X5m5qu3QTrN3yeTHg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "027d276a-61f3-458c-a820-3742225a790b",
                            TwoFactorEnabled = false,
                            UserName = "cristopher@gmail.com"
                        },
                        new
                        {
                            Id = "121653b8-4b3f-4e40-8e00-e2ee0400f1d8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cdd61c9d-a035-42b0-824a-8113d22e3758",
                            Email = "rodolfo@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "RODOLFO@GMAIL.COM",
                            NormalizedUserName = "RODOLFO@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENEyUSOSeok71WLp/49dnKtGDhtCn4cUoF+avEtofyHjvnE3H/Ug2sV5qZKYGhLsow==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a9edcea7-af31-40e5-a554-c49e01bc34bd",
                            TwoFactorEnabled = false,
                            UserName = "rodolfo@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "97b3151c-f939-4f89-9679-1f37116740d1",
                            RoleId = "32f5c337-16be-44ad-8c87-d13d7ddeac28"
                        },
                        new
                        {
                            UserId = "f1e29e01-a4f9-4be5-8c57-9b248d16570c",
                            RoleId = "aa61e93c-ab9d-46f4-b3a7-ef5463a9237b"
                        },
                        new
                        {
                            UserId = "121653b8-4b3f-4e40-8e00-e2ee0400f1d8",
                            RoleId = "aa786d24-1a3f-4f57-b7f9-2a19a99d4823"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.DetallesDistribucion", b =>
                {
                    b.HasOne("Frutos_del_Terraba_Api.Models.Distribucion", "Distribucion")
                        .WithMany("DetallesDistribuciones")
                        .HasForeignKey("Id_distribucion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Frutos_del_Terraba_Api.Models.Inventario", "Inventario")
                        .WithMany("DetallesDistribuciones")
                        .HasForeignKey("Id_inventario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Distribucion");

                    b.Navigation("Inventario");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.DetallesPedido", b =>
                {
                    b.HasOne("Frutos_del_Terraba_Api.Models.Pedido", "Pedido")
                        .WithMany("DetallesPedidos")
                        .HasForeignKey("Id_pedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Frutos_del_Terraba_Api.Models.Producto", "Producto")
                        .WithMany("DetallesPedidos")
                        .HasForeignKey("Id_producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Distribucion", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Inventario", b =>
                {
                    b.HasOne("Frutos_del_Terraba_Api.Models.Producto", "Producto")
                        .WithMany("Inventarios")
                        .HasForeignKey("Id_producto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Pedido", b =>
                {
                    b.HasOne("Frutos_del_Terraba_Api.Models.Proveedor", "Proveedor")
                        .WithMany("Pedidos")
                        .HasForeignKey("Id_proveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Producto", b =>
                {
                    b.HasOne("Frutos_del_Terraba_Api.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("Id_categoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Reporte", b =>
                {
                    b.HasOne("Frutos_del_Terraba_Api.Models.Producto", "Producto")
                        .WithMany("Reportes")
                        .HasForeignKey("Id_producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Distribucion", b =>
                {
                    b.Navigation("DetallesDistribuciones");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Inventario", b =>
                {
                    b.Navigation("DetallesDistribuciones");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Pedido", b =>
                {
                    b.Navigation("DetallesPedidos");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Producto", b =>
                {
                    b.Navigation("DetallesPedidos");

                    b.Navigation("Inventarios");

                    b.Navigation("Reportes");
                });

            modelBuilder.Entity("Frutos_del_Terraba_Api.Models.Proveedor", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
